apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: member-center-fe
  name: member-center-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: times-registry.cn-shenzhen.cr.aliyuncs.com:443/m-center-uat/member-center-fe:GIT_BRANCH_AS_TAG_TIMESTAMP
        name: member-center-fe
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: member-center-fe-conf
          subPath: nginx.conf
      volumes:
      - configMap:
          name: member-center-fe-conf
        name: member-center-fe-conf