export default [
  {
    title: "项目管理",
    authKeys: ["menu_project"],
    icon: require("@/assets/img/menu/icon_xiangmuguanli.png"),
    menuKey: "",
    group: "kjgl",
    name: "second",
    hasChild: "project",
    path: "/project/second",
    children:[
      {
        title: "项目列表",
        authKeys: ["menu_project"],
        menuKey: "project ",
        path: "/project/second/projectList",
      },
      {
        title: "社区信息管理",
        authKeys: ["menu_project"],
        menuKey: "projectInfo ",
        path: "/project/second/projectInfo",
      },
    ]
  },
  {
    title: "空间管理",
    authKeys: ["menu_space"],
    icon: require("@/assets/img/menu/icon_kongjianguanli.png"),
    menuKey: "space",
    group: "kjgl",
    path: "/space",
  },
  {
    title: "标签管理",
    authKeys: ["menu_space_label"],
    icon: require("@/assets/img/menu/icon_biaoqianguanli.png"),
    menuKey: "label",
    group: "kjgl",
    path: "/label",
  },
  {
    title: "区域管理",
    authKeys: ["menu_area"],
    icon: require("@/assets/img/menu/icon_quyuguanli.png"),
    menuKey: "area",
    group: "qygl",
    path: "/area",
  },
  {
    title: "公司库",
    authKeys: ["menu_company"],
    icon: require("@/assets/img/menu/icon_gongsiku.png"),
    menuKey: "company",
    group: "gsgl",
    path: "/company",
  },
  {
    title: "B端用户管理",
    authKeys: ["menu_b_user"],
    icon: require("@/assets/img/menu/icon_buser.png"),
    menuKey: "clientUser",
    group: "yhgl",
    path: "/user/hcmUser",
  },
  {
    title: "C端用户管理",
    authKeys: ["menu_c_user"],
    icon: require("@/assets/img/menu/icon_cuser.png"),
    menuKey: "clientUser",
    group: "yhgl",
    path: "/user/clientUser",
  },
  {
    title: "个人中心",
    authKeys: [""],
    icon: require("@/assets/img/menu/icon_cuser.png"),
    menuKey: "userInfo",
    group: "grzx",
    path: "/user/userInfo",
  },
  {
    title: "物业公告",
    authKeys: ["app_notice"],
    icon: require("@/assets/img/menu/icon_wuyegonggao.png"),
    menuKey: "propertyNotice",
    group: "wygg",
    path: "/propertyNotice",
  },
  {
    title: "类型管理",
    authKeys: [""],
    icon: require("@/assets/img/menu/icon_leixingguanli.png"),
    menuKey: "typeManage",
    group: "wygg",
    path: "/propertyNotice/typeManage",
  },
  {
    title: "开屏页设置",
    authKeys: ["app_advertising"],
    icon: require("@/assets/img/menu/icon_kaipingye.png"),
    menuKey: "",
    group: "gggg",
    hasChild: "advertise",
    name: "second",
    path: "/advertise/second",
    children:[
      {
        title: "AppC开屏页设置",
        authKeys: ["app_advertising"],
        menuKey: "guidePageAppC ",
        path: "/advertise/second/guidePageAppC",
      },
      {
        title: "AppB开屏页设置",
        authKeys: ["app_advertising"],
        menuKey: "guidePageAppB ",
        path: "/advertise/second/guidePageAppB",
      },
    ]
  },
  {
    title: "弹窗管理",
    authKeys: ["app_advertising"],
    icon: require("@/assets/img/menu/icon_tanchuang.png"),
    menuKey: "popUp",
    group: "gggg",
    path: "/advertise/popUp",
  },
  {
    title: "广告区域管理",
    authKeys: ["app_advertising"],
    icon: require("@/assets/img/menu/icon_guanggaoquyu.png"),
    menuKey: "advertiseArea",
    group: "gggg",
    path: "/advertise/advertiseArea",
  },
  {
    title: "广告推送管理",
    authKeys: ["app_advertising"],
    icon: require("@/assets/img/menu/icon_guanggaotuisong.png"),
    menuKey: "advertisePush",
    group: "gggg",
    path: "/advertise/advertisePush",
  },
  {
    title: "邻里生活管理",
    authKeys: ["app_advertising"],
    icon: require("@/assets/img/menu/icon_linglishenghuo.png"),
    menuKey: "neighborhoodLife",
    group: "gggg",
    path: "/advertise/neighborhoodLife",
  },
  {
    title: "邻里星选管理",
    authKeys: ["app_advertising"],
    icon: require("@/assets/img/menu/icon_linglixingxuan.png"),
    menuKey: "neighborhoodStarChoose",
    group: "gggg",
    path: "/advertise/neighborhoodStarChoose",
  },
  {
    title: "邻里推荐管理",
    authKeys: ["app_advertising"],
    icon: require("@/assets/img/menu/icon_linglituijian.png"),
    menuKey: "neighborhoodRecommend",
    group: "gggg",
    path: "/advertise/neighborhoodRecommend",
  },
  {
    title: "AppB增值推广管理",
    authKeys: ["app_advertising"],
    icon: require("@/assets/img/menu/icon_zengzhituiguang.png"),
    menuKey: "addPromotion",
    group: "gggg",
    path: "/advertise/addPromotion",
  },
  {
    title: "App版本列表",
    authKeys: [""],
    icon: require("@/assets/img/menu/icon_banbenfabu.png"),
    menuKey: "version",
    group: "bb",
    path: "/version",
  },
  {
    title: "活动列表",
    authKeys: [""],
    icon: require("@/assets/img/menu/icon_huodongliebiao.png"),
    menuKey: "activity",
    group: "hdgl",
    path: "/activity",
  },
  {
    title: "分类管理",
    authKeys: [""],
    icon: require("@/assets/img/menu/icon_fenleiguanli.png"),
    menuKey: "classifyManage",
    group: "hdgl",
    path: "/classifyManage",
  },
  {
    title: "访客列表",
    authKeys: [""],
    icon: require("@/assets/img/menu/icon_fangke.png"),
    menuKey: "visitor",
    group: "fkgl",
    path: "/visitor",
  },
  {
    title: "住户档案",
    authKeys: ["app_owner_archive"],
    icon: require("@/assets/img/menu/icon_zhuhudangan.png"),
    menuKey: "resident",
    group: "zhda",
    path: "/resident",
  },
  {
    title: "标签管理",
    authKeys: ["app_owner_archive"],
    icon: require("@/assets/img/menu/icon_zhuhudangan.png"),
    menuKey: "residentLabel",
    group: "zhda",
    path: "/residentLabel",
  },
  {
    title: "微应用列表",
    authKeys: [""],
    icon: require("@/assets/img/menu/icon_weiyingyong.png"),
    menuKey: "microApplication",
    group: "wyy",
    path: "/micro",
  },
  {
    title: "资源包列表",
    authKeys: [""],
    menuKey: "resourcePackage",
    icon: require("@/assets/img/menu/icon_ziyuanbao.png"),
    group: "wyy",
    path: "/resourcePackage",
  },
  {
    title: "区域人员配置",
    authKeys: ["app_area_emp"],
    menuKey: "areaPersonnel",
    icon: require("@/assets/img/menu/icon_ziyuanbao.png"),
    group: "qyry",
    path: "/areaPersonnel",
  },
  //运营管理开始
  {
    title: '帮助中心管理',
    authKeys: [''],
    menuKey: 'helpCenter',
    icon: require('@/assets/img/menu/icon_ziyuanbao.png'),
    group: 'yyxx',
    path: '/operationsManagement/helpCenter',
  },
  {
    title: '产品简介配置',
    authKeys: [''],
    menuKey: 'productPresentation',
    icon: require('@/assets/img/menu/icon_ziyuanbao.png'),
    group: 'yyxx',
    path: '/operationsManagement/productPresentation',
  },
  {
    title: '商务合作配置',
    authKeys: [''],
    menuKey: 'businessCooperation',
    icon: require('@/assets/img/menu/icon_ziyuanbao.png'),
    group: 'yyxx',
    path: '/operationsManagement/businessCooperation',
  },
  {
    title: '隐私政策配置',
    authKeys: [''],
    menuKey: 'privacyPolicy',
    icon: require('@/assets/img/menu/icon_ziyuanbao.png'),
    group: 'yyxx',
    path: '/operationsManagement/privacyPolicy',
  },
  {
    title: '注销协议配置',
    authKeys: [''],
    menuKey: 'mutualCancellation',
    icon: require('@/assets/img/menu/icon_ziyuanbao.png'),
    group: 'yyxx',
    path: '/operationsManagement/mutualCancellation',
  },
  //运营管理结束
  //
  {
    title: "装修申请",
    authKeys: ['menu_decorate_see'],
    icon: require("@/assets/img/menu/icon_zhuangxiuguanli.png"),
    menuKey: "decorateManagement",
    group: "zxsq",
    path: "/decorateManagement",
  },
  {
    title: "巡检点管理",
    authKeys: ['menu_quality_point_manage'],
    icon: require("@/assets/img/menu/icon_xunjiandianguanli.png"),
    menuKey: "inspectionPoint",
    group: "pxgl",
    path: "/qualityManagement/inspectionPoint",
  },
  {
    title: "标准管理",
    authKeys: ['menu_quality_stand_manage'],
    icon: require("@/assets/img/menu/icon_biaozhunguanli.png"),
    menuKey: "standard",
    group: "pxgl",
    path: "/qualityManagement/standard",
  },
  {
    title: "主题管理",
    authKeys: ["menu_quality_topic_manage"],
    icon: require("@/assets/img/menu/icon_zhutiguanli.png"),
    menuKey: "",
    group: "pxgl",
    hasChild: "qualityManagement",
    path: "/qualityManagement/inspectionTheme",
    children:[
      {
        title: "巡查主题",
        authKeys: [""],
        menuKey: "inspectionTheme ",
        path: "/qualityManagement/inspectionTheme",
      },
      {
        title: "质检主题",
        authKeys: [""],
        menuKey: "qualityControlTheme ",
        path: "/qualityManagement/qualityControlTheme",
      },
      {
        title: "专项主题",
        authKeys: [""],
        menuKey: "specialCheckTheme ",
        path: "/qualityManagement/specialCheckTheme",
      },
      {
        title: "装修巡查主题",
        authKeys: [""],
        menuKey: "decorationInspectionTheme ",
        path: "/qualityManagement/decorationInspectionTheme",
      },
    ]
  },
  {
    title: "巡查管理",
    authKeys: ['menu_quality_inspect'],
    icon: require("@/assets/img/menu/icon_xunjianguanli.png"),
    menuKey: "inspection",
    group: "pxgl",
    path: "/qualityManagement/inspection",
  },
  {
    title: "质检管理",
    authKeys: ["menu_quality_quality"],
    icon: require("@/assets/img/menu/icon_zhijianguanli.png"),
    menuKey: "",
    group: "pxgl",
    hasChild: "qualityinspection",
    path: "/qualityManagement/qualityControlHead",
    children:[
      {
        title: "总部抽查",
        authKeys: ["menu_city_company"],
        menuKey: "qualityControlHead ",
        path: "/qualityManagement/qualityControlHead",
      },
      {
        title: "城市公司自检",
        authKeys: ["menu_head_company"],
        menuKey: "qualityControlCity ",
        path: "/qualityManagement/qualityControlCity",
      },
    ]
  },


  {
    title: "专项管理",
    authKeys: ['menu_quality_special'],
    icon: require("@/assets/img/menu/icon_zhuanxiangguanli.png"),
    menuKey: "specialCheck",
    group: "pxgl",
    path: "/qualityManagement/specialCheck",
  },
  {
    title: "装修巡查管理",
    authKeys: ['menu_quality_decorate'],
    icon: require("@/assets/img/menu/icon_zhuangxiuguanli.png"),
    menuKey: "decorate",
    group: "pxgl",
    path: "/qualityManagement/decorate",
  },

  {
    title: "放行条审核",
    authKeys: [''],
    icon: require("@/assets/img/menu/icon_fangxingtiao.png"),
    menuKey: "",
    group: "fxt",
    path: "/releasePass",
  },
];
